version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - megaqc-dev
    depends_on:
      - postgres
    environment:
      - MEGAQC_PRODUCTION=0
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=megaqc_dev
      - DB_USER=megaqc_user
      - DB_PASS=megaqc_dev_password
    user: "1000:1000"

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: megaqc_dev
      POSTGRES_USER: megaqc_user
      POSTGRES_PASSWORD: megaqc_dev_password
    networks:
      - megaqc-dev
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  megaqc-dev: 